name: Build and Publish Docker Images

on:
  push:
    tags:
      - '*.*.*'  # This triggers the workflow on tags like 1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from tag
      id: extract_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          your-dockerhub-username/yamnet:${{ env.RELEASE_VERSION }}
          your-dockerhub-username/yamnet:latest

    - name: Bump version in pyproject.toml
      run: |
        sed -i "s/^version = \".*\"/version = \"${{ env.RELEASE_VERSION }}\"/" pyproject.toml

    - name: Commit version bump
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -am "Bump version to ${{ env.RELEASE_VERSION }}"
        git push origin main

    - name: Create a release on GitHub
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        body: |
          Release ${{ env.RELEASE_VERSION }} is out now!
        draft: false
        prerelease: false
